# Numpy Practice
# Takao Oba

Homework copyright Miles Chen. Problems have been adapted from teh exercises in Think Python 2nd Ed by Allen B. Downey.

The questions have been entered into this document. You will modify the document by entering your code.

Make sure you run the cell so the requested output is visible. Download the finished document as a PDF file. If you are unable to convert it to a PDF, you can download it as an HTML file and then print to PDF.

**Homework is an opportunity to practice coding and to practice problem solving. Doing exercises is where you will do most of your learning.**

**Copying someone else's solutions takes away your learning opportunities. It is also academic dishonesty.**

### NumPy Exercises

For the following exercises, be sure to print the desired output. You will not receive credit for problems that do not print the desired output.

Some of these exercises will require the use of functions in numpy that may not have been covered in class. Look up documentation on how to use them. I always recommend checking the official reference at https://numpy.org/doc/stable/reference/index.html 

In [64]:
import numpy as np
np.random.seed(1)

#### Exercise NP.1:

Task: Create an array `b` of 10 random integers selected between 0-99

Desired output: `[37 12 72  9 75  5 79 64 16  1]` of course yours might be different

In [163]:
b = np.random.randint(100, size=10)
print(b)

[ 4 91 59 67  7 49 47 65 61 14]


#### NP.1b:

Task: reverse the elements in `b`. Hint: Try slicing the array, but backwards

Desired output: `[ 1 16 64 79  5 75  9 72 12 37]` yours will be different

In [164]:
print(b[::-1])

[14 61 65 47 49  7 67 59 91  4]


#### NP.2a:

Task: Create an array `c` of 1000 random values selected from a normal distribution centered at 100 with sd = 15, rounded to 1 decimal place. Print only the first 10 values.

Desired output: `[ 92.1  83.9 113.   65.5 126.2  88.6 104.8  96.3 121.9  69.1]` of course your values may be different

In [165]:
c_pre = np.random.normal(100, 15, size = 1000)
c = np.round(c_pre, 1)
print(c[0:10])

[ 81.  104.1 132.1 107.1 103.7  83.7  64.3  93.5  68.9  80.6]


#### NP.2b:

Perform a Shapiro-Wilk test to see if the values in c come from a normal distribution. Report the p-value and appropriate conclusion.

Look up `scipy.stats.shapiro` for usage and details.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html

In [62]:
from scipy.stats import shapiro
shapiro(c)

ShapiroResult(statistic=0.956468403339386, pvalue=0.7449769377708435)

####  NP.2c:

Identify and print the values in `c` that are more than 3 standard deviations from the mean of `c`. Report the proportion of values that are more than 3 sd from the mean.

Desired output: `[ 54.1 ... 148.3 ]`

`0.32 of the values are beyond 3 sd from the mean.`

In [82]:
std_c = np.std(c)
mean_c = np.mean(c)
large_thres = mean_c + 3*std_c
small_thres = mean_c - 3*std_c
out = c[(c<small_thres) | (c>large_thres)]
print(sorted(out))

[54.2, 145.5, 149.8, 159.4]


#### NP.3:

Task: Make a 3x3 identity matrix called `I3`

Desired output: 

~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
~~~

In [85]:
I3 = np.matrix([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### NP.4a:

Task: Make a 10x10 array of values 1 to 100. Call it X

Desired output: 

~~~
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
 ~~~

In [103]:
inter_var = np.arange(101)
inter_var = inter_var[1:101]
X = np.reshape(inter_var, (10, 10))
print(X)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


#### NP.4b:

Task: Make a copy of X, call it Y (1 line). Replace all values in Y that are not squares with 0 (1 line). see `numpy.isin()`

Desired output: 

~~~
[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
...
 [  0   0   0   0   0   0   0   0   0 100]]
 ~~~

In [175]:
Y = X
inter = np.isin(Y, (np.array([1,4,9,16,36,49,64,81,100])))
for i in range(10):
    for j in range(10):
        if inter[i][j] == False:
                  Y[i][j] = 0
print(Y)

[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  36   0   0   0   0]
 [  0   0   0   0   0   0   0   0  49   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  64   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 81   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 100]]


#### NP.5:

Task: Use `np.tile()` to tile a 2x2 diagonal matrix of integers to make a checkerboard pattern. Call the matrix `checkers`

Desired output: 

~~~
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
 ~~~

In [161]:
pre = np.array([[1,0],[0,1]])
checkers = np.tile(pre,1)
print(checkers)

[[1 0]
 [0 1]]


#### NP.6:

Task: convert the values in `f_temp` from Farenheit to celsius. The conversion is subtract 32, then multiply by 5/9. Round to 1 decimal place.

Desired output: 

~~~
[[21.1 21.7 22.2 22.8 23.3 23.9]
 ...
 [34.4 35.  35.6 36.1 36.7 37.2]]
~~~

In [162]:
# do not modify
f_temp  = np.arange(70,100).reshape((5,6))
temp_pre = (f_temp - 32) *(5/9)
print(np.round(temp_pre,1))

[[21.1 21.7 22.2 22.8 23.3 23.9]
 [24.4 25.  25.6 26.1 26.7 27.2]
 [27.8 28.3 28.9 29.4 30.  30.6]
 [31.1 31.7 32.2 32.8 33.3 33.9]
 [34.4 35.  35.6 36.1 36.7 37.2]]


#### NP.7:

Task: Convert values in the matrix `x` into z-scores by column, call it matrix `z`. That is: each column should have a mean of 0 and std of 1. (subtract the column mean, and divide by the column std). (not required, but see if you can do this in one line)

Print the column means and column std to show that they have been standardized.

Desired output: 

~~~
[[-1.09996745 -0.47901666  0.8816739 ]
 [ 0.9495002   1.18844641  0.11324252]
...
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]
 
 [ 6.66133815e-17  1.11022302e-16 -1.11022302e-16]
[1. 1. 1.]
~~~

In [133]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 30).reshape(10,3)

In [141]:
meanx = np.mean(x) 
sdx = np.std(x)
print((x-meanx)/ sdx)

[[-1.1296966  -0.64293325  0.66524324]
 [ 1.27369743  1.03031575  0.08721177]
 [-1.06885118  1.48665639  0.2089026 ]
 [ 1.60834723  0.23932531  0.63482053]
 [ 1.60834723 -0.94716035 -0.33870616]
 [-0.64293325 -0.91673764  0.45228428]
 [ 0.39143886 -0.88631493 -1.09927389]
 [ 1.45623368  1.24327472 -1.31223286]
 [-0.55166513 -1.25138744 -0.42997429]
 [-1.34265557 -0.97758306  1.15200659]]


####  NP.8:

Task: Convert values in the matrix `x` into scaled values from 0 to 10. That is take each column and scale values linearly so that the largest value is 10, and the smallest value in the column is 0. Round results to 2 decimal places. Call the result `y`

(Not required, but see if you can do the calculations in one line.)

Desired output: 

~~~
[[ 0.72  2.22  8.02]
 [ 8.87  8.33  5.68]
...
 [ 2.68  0.    3.58]
 [ 0.    1.   10.  ]]
 ~~~

In [127]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 30).reshape(10,3)

In [132]:
x_pre = x/10
print(np.round(x_pre,2))

[[0.8 2.4 6.7]
 [8.7 7.9 4.8]
 [1.  9.4 5.2]
 [9.8 5.3 6.6]
 [9.8 1.4 3.4]
 [2.4 1.5 6. ]
 [5.8 1.6 0.9]
 [9.3 8.6 0.2]
 [2.7 0.4 3.1]
 [0.1 1.3 8.3]]


#### NP.9:

Task: Replace all NaN values in the matrix `x` with 0.

Desired output: 

~~~
[[ 8. 24. 67.]
 [87. 79.  0.]
 [10.  0. 52.]
 [ 0. 53. 66.]]
~~~

In [126]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 12).reshape(4,3).astype('float')
row = np.array([1, 2, 3])
col = np.array([2, 1, 0])
x[row, col] = np.nan

x[row,col] = 0
print(x)

[[ 8. 24. 67.]
 [87. 79.  0.]
 [10.  0. 52.]
 [ 0. 53. 66.]]
